name: Build and Deploy to Render

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 24

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile   # explicitly point to Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/shri-sells:latest
            ${{ secrets.DOCKER_USERNAME }}/shri-sells:${{ github.sha }}

      - name: Trigger Render deploy
        id: deploy
        run: |
          echo "Triggering Render deployment..."
          response=$(curl -s -o response.json -w "%{http_code}" -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys)
          echo "Render API responded with status: $response"
          cat response.json
